# mantra Configuration for Complex Examples
# This example uses OpenRouter with Claude-3 Sonnet

# Model configuration
model = "openai/gpt-oss-20b"

# OpenRouter API endpoint
url = "https://openrouter.ai/api/v1"

# Output directory
dest = "../complex_mantra"

# API key from environment variable
api_key = "${OPENROUTER_API_KEY}"

# Debug logging to see generation details
log_level = "error"

# OpenRouter-specific configuration
[openrouter]
providers = ["fireworks"]
