# Model configuration
model = "inception/mercury-coder"

# OpenRouter API endpoint
url = "https://openrouter.ai/api/v1"

# Output directory
dest = "../simple_mantra"

# API key from environment variable
api_key = "${OPENROUTER_API_KEY}"

# OpenRouter-specific configuration
# [openrouter]
# providers = ["fireworks"]
